#  _                      _            _
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   <
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|
#
source = $HOME/.config/hypr/colors/tokyonight_night.conf

$font = JetBrainsMono Nerd Font Propo

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# Auth
auth {
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning...
    retry_delay = 250 # in milliseconds
  }
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.local/share/backgrounds/twist.png
  blur_passes = 0
  color = $background
}

# TIME
label {
  monitor =
  text = $TIME
  color = $foreground
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $foreground
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $background
  font_color = $foreground
  fade_on_empty = false
  placeholder_text = <span foreground="##$foregroundAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
