$foreground = rgb(c0caf5)
$foregroundAlpha = c0caf5

$background = rgb(1a1b26)
$backgroundAlpha = 1a1b26

$accent = rgb(7aa2f7)
$accentAlpha = 7aa2f7

$red = rgb(f7768e)
$redAlpha = f7768e

$yellow = rgb(e0af68)
$yellowAlpha = e0af68


